version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: safetyswift
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: localminio
      MINIO_ROOT_PASSWORD: localminiopw
    command: server --console-address :9001 /data
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data

  mailpit:
    image: axllent/mailpit:v1.14
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE}
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
    command: pnpm --filter @safetyswift/api dev

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - api
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE}
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    command: pnpm --filter @safetyswift/web dev

volumes:
  db-data:
  minio-data:
